name: Test Audit
on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Dockerfile.base
      run: docker build . --file Dockerfile.base --tag jakejarvis/chrome-headless:latest
    - name: Run audit on https://ikea.cn/cn/zh/
      uses: ./
      with:
        url: 'https://www.ikea.cn/cn/zh/'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
